import { createContext, useContext, useState } from "react";

type Lang = "en" | "fr";

const T = {
  en: {
    // Nav
    "nav.thisMonth": "This Month",
    "nav.howItWorks": "How It Works",
    "nav.suggestions": "Suggestions",
    "nav.suggestBook": "Suggest a book",
    "nav.vote": "Vote for next month",
    "nav.editPicture": "Edit profile picture",
    "nav.signOut": "Sign out",
    // Hero
    "hero.tagline": "Read one book together every month.",
    // How it works
    "how.title": "How it works",
    "how.discover.title": "Discover",
    "how.discover.desc": "Explore this month's Book of the Month, suggest future reads, and help the community choose what comes next.",
    "how.read.title": "Read",
    "how.read.desc": "Take your time reading, then mark the book as finished to unlock the discussion.",
    "how.share.title": "Connect",
    "how.share.desc": "Meet in person or unlock the online conversation after you finish the book.",
    // Book of month
    "book.label": "Book of the Month",
    "book.noBook.title": "Next Book Coming Soon",
    "book.noBook.desc": "The community is selecting this month's book. Voting opens shortly.",
    "book.noBook.hint": "Be ready to join the discussion as soon as it's announced.",
    "book.readMore": "Read more",
    "book.showLess": "Show less",
    "book.signInPrompt.link": "Sign in",
    "book.signInPrompt.text": "to track your progress and join the discussion.",
    // Stats strip
    "stats.reading": "reading",
    "stats.finished": "finished",
    "stats.reviews": "reviews",
    "stats.review": "review",
    // Reading status
    "status.label": "My Status",
    "status.reading": "Reading",
    "status.finished": "Finished",
    "status.toast.reading": "Marked as reading.",
    "status.toast.finished": "Marked as finished.",
    "status.toast.token": "+1 Token — book finished!",
    "status.error": "Couldn't update status. Try again.",
    // Reviews
    "reviews.title": "Community Reviews",
    "reviews.yourReview": "Your Review",
    "reviews.shareThoughts": "Share Your Thoughts",
    "reviews.editReview": "Edit Your Review",
    "reviews.postReview": "Post Review",
    "reviews.updateReview": "Update Review",
    "reviews.saving": "Saving…",
    "reviews.cancel": "Cancel",
    "reviews.noOther.title": "No other reviews yet",
    "reviews.noOther.hint": "Your review appears in the section above. Other members' reviews will show here.",
    "reviews.ratingLabel": "How would you rate it?",
    "reviews.thoughtsLabel": "Your thoughts",
    "reviews.optional": "optional",
    "reviews.placeholder": "What did you think about",
    "reviews.charsLeft": "left",
    "reviews.ratingError": "Please select a star rating before posting.",
    "reviews.posted": "Review posted.",
    "reviews.updated": "Review updated!",
    "reviews.deleted": "Review removed.",
    "reviews.saveError": "Couldn't save your review. Please try again.",
    "reviews.deleteError": "Couldn't delete review. Try again.",
    "reviews.token": "+1 Token — thanks for your review!",
    "rating.1": "Poor", "rating.2": "Fair", "rating.3": "Good", "rating.4": "Great", "rating.5": "Amazing",
    // Voting
    "vote.label": "Vote for Next Month",
    "vote.title": "What should we read next?",
    "vote.firstVote": "Be the first to vote!",
    "vote.voted": "members have voted",
    "vote.changeVote": "You can change your vote anytime",
    "vote.button": "Vote for this book",
    "vote.voted.label": "Voted",
    "vote.remove": "Remove vote",
    "vote.cast": "Vote cast.",
    "vote.updated": "Vote updated.",
    "vote.removed": "Vote removed.",
    "vote.error": "Couldn't save vote. Please try again.",
    // Community picks
    "picks.label": "Community Picks",
    "picks.subtitle": "Support the books you'd like to read next. Open your profile to add your own suggestion.",
    "picks.supports": "supports",
    "picks.support": "Support",
    "picks.empty.title": "No suggestions yet",
    "picks.empty.hint": "Open your profile to be the first to suggest a book.",
    "picks.supportToast": "1 Token used to support this suggestion.",
    "picks.supportError": "Couldn't support this suggestion. Try again.",
    "picks.leading": "Leading",
    // Suggestion form / modal
    "suggest.modal.title": "Suggest a book",
    "suggest.tokenRules.finish": "Finish a Book of the Month",
    "suggest.tokenRules.receive": "Receive a support on your suggestion",
    "suggest.tokenRules.spend": "Support someone else's book",
    "suggest.tokenRules.earn": "+1 token",
    "suggest.tokenRules.cost": "−1 token",
    "suggest.tokenRules.limit": "Max 3 suggestions per month · resets at the start of each month",
    "suggest.form.title": "Title",
    "suggest.form.author": "Author",
    "suggest.form.coverUrl": "Cover image URL",
    "suggest.form.why": "Why this book?",
    "suggest.form.titlePlaceholder": "e.g. The Great Gatsby",
    "suggest.form.authorPlaceholder": "e.g. F. Scott Fitzgerald",
    "suggest.form.coverPlaceholder": "https://…",
    "suggest.form.whyPlaceholder": "A short reason why this book would make a great pick…",
    "suggest.form.required": "Title and author are required.",
    "suggest.form.submit": "Submit suggestion",
    "suggest.form.update": "Update",
    "suggest.form.saving": "Saving…",
    "suggest.form.cancel": "Cancel",
    "suggest.form.edit": "Edit your suggestion",
    "suggest.added": "Suggestion added.",
    "suggest.updated": "Suggestion updated.",
    "suggest.removed": "Suggestion removed.",
    "suggest.error": "Couldn't save suggestion. Try again.",
    // Past reads
    "past.title": "Past Reads",
    "past.subtitle": "Books the community has read together, one month at a time.",
    "past.archive": "A growing archive of shared reading.",
    "past.back": "Back",
    "past.viewReviews": "View reviews",
    "past.hideReviews": "Hide reviews",
    "past.noReviews": "No reviews were written for this book.",
    "past.empty.title": "Nothing here yet",
    "past.empty.hint": "The archive will grow as each month passes.",
    "past.closing": "Every month adds a new chapter to the club.",
    // Footer
    "footer.tagline": "Read one book together every month.",
    "footer.thisMonth": "This Month",
    "footer.howItWorks": "How It Works",
    "footer.suggestions": "Suggestions",
    "footer.pastReads": "Past Reads",
    "footer.copyright": "© 2026 The Blue Book Club — created by Ariane S.",
    // Auth
    "auth.continue": "Continue with Google",
    "auth.signingIn": "Signing in…",
    "auth.signIn": "Sign in",
    "auth.signOut.toast": "You've been signed out.",
    "auth.signIn.error": "Sign-in failed: ",
    // Notifications
    "notifications.title": "Notifications",
    "notifications.unread": "unread",
    "notifications.empty": "No notifications yet.",
    "notifications.replied": "replied to your review of",
    // Replies
    "reply.placeholder": "Write a reply…",
    "reply.post": "Reply",
    "reply.posting": "Posting…",
    "reply.cancel": "Cancel",
    "reply.posted": "Reply posted.",
    "reply.error": "Couldn't post reply.",
    "reply.count": "repl",
    // Discussion gate
    "past.discussionGate": "Mark this book as finished to join the discussion.",
  },
  fr: {
    // Nav
    "nav.thisMonth": "Ce mois",
    "nav.howItWorks": "Comment ça marche",
    "nav.suggestions": "Suggestions",
    "nav.suggestBook": "Suggérer un livre",
    "nav.vote": "Voter pour le mois prochain",
    "nav.editPicture": "Modifier la photo de profil",
    "nav.signOut": "Se déconnecter",
    // Hero
    "hero.tagline": "Lire un livre ensemble chaque mois.",
    // How it works
    "how.title": "Comment ça marche",
    "how.discover.title": "Découvrir",
    "how.discover.desc": "Explorez le livre du mois, suggérez de futures lectures et aidez la communauté à choisir la prochaine sélection.",
    "how.read.title": "Lire",
    "how.read.desc": "Lisez à votre rythme, puis marquez le livre comme terminé pour débloquer la discussion.",
    "how.share.title": "Connecter",
    "how.share.desc": "Rencontrez-vous en personne ou déverrouillez la conversation en ligne après avoir terminé le livre.",
    // Book of month
    "book.label": "Livre du mois",
    "book.noBook.title": "Prochain livre bientôt annoncé",
    "book.noBook.desc": "La communauté sélectionne le livre du mois. Le vote ouvrira bientôt.",
    "book.noBook.hint": "Soyez prêt à rejoindre la discussion dès l'annonce.",
    "book.readMore": "Lire plus",
    "book.showLess": "Réduire",
    "book.signInPrompt.link": "Se connecter",
    "book.signInPrompt.text": "pour suivre votre progression et rejoindre la discussion.",
    // Stats strip
    "stats.reading": "en lecture",
    "stats.finished": "terminé",
    "stats.reviews": "avis",
    "stats.review": "avis",
    // Reading status
    "status.label": "Mon statut",
    "status.reading": "En lecture",
    "status.finished": "Terminé",
    "status.toast.reading": "Marqué en lecture.",
    "status.toast.finished": "Marqué comme terminé.",
    "status.toast.token": "+1 jeton — livre terminé !",
    "status.error": "Impossible de mettre à jour le statut. Réessayez.",
    // Reviews
    "reviews.title": "Avis de la communauté",
    "reviews.yourReview": "Votre avis",
    "reviews.shareThoughts": "Partagez votre avis",
    "reviews.editReview": "Modifier votre avis",
    "reviews.postReview": "Publier",
    "reviews.updateReview": "Mettre à jour",
    "reviews.saving": "Enregistrement…",
    "reviews.cancel": "Annuler",
    "reviews.noOther.title": "Pas encore d'autres avis",
    "reviews.noOther.hint": "Votre avis apparaît dans la section ci-dessus. Les avis des autres membres apparaîtront ici.",
    "reviews.ratingLabel": "Comment évaluez-vous ce livre ?",
    "reviews.thoughtsLabel": "Vos impressions",
    "reviews.optional": "optionnel",
    "reviews.placeholder": "Qu'avez-vous pensé de",
    "reviews.charsLeft": "restants",
    "reviews.ratingError": "Veuillez sélectionner une note avant de publier.",
    "reviews.posted": "Avis publié.",
    "reviews.updated": "Avis mis à jour !",
    "reviews.deleted": "Avis supprimé.",
    "reviews.saveError": "Impossible d'enregistrer votre avis. Réessayez.",
    "reviews.deleteError": "Impossible de supprimer l'avis. Réessayez.",
    "reviews.token": "+1 jeton — merci pour votre avis !",
    "rating.1": "Mauvais", "rating.2": "Passable", "rating.3": "Bien", "rating.4": "Très bien", "rating.5": "Excellent",
    // Voting
    "vote.label": "Voter pour le mois prochain",
    "vote.title": "Que devrions-nous lire ensuite ?",
    "vote.firstVote": "Soyez le premier à voter !",
    "vote.voted": "membres ont voté",
    "vote.changeVote": "Vous pouvez changer votre vote à tout moment",
    "vote.button": "Voter pour ce livre",
    "vote.voted.label": "Voté",
    "vote.remove": "Retirer le vote",
    "vote.cast": "Vote enregistré.",
    "vote.updated": "Vote modifié.",
    "vote.removed": "Vote retiré.",
    "vote.error": "Impossible d'enregistrer le vote. Réessayez.",
    // Community picks
    "picks.label": "Choix de la communauté",
    "picks.subtitle": "Soutenez les livres que vous aimeriez lire. Ouvrez votre profil pour ajouter votre suggestion.",
    "picks.supports": "soutiens",
    "picks.support": "Soutenir",
    "picks.empty.title": "Aucune suggestion pour l'instant",
    "picks.empty.hint": "Ouvrez votre profil pour être le premier à suggérer un livre.",
    "picks.supportToast": "1 jeton utilisé pour soutenir cette suggestion.",
    "picks.supportError": "Impossible de soutenir cette suggestion. Réessayez.",
    "picks.leading": "En tête",
    // Suggestion form / modal
    "suggest.modal.title": "Suggérer un livre",
    "suggest.tokenRules.finish": "Terminer un livre du mois",
    "suggest.tokenRules.receive": "Recevoir un soutien sur votre suggestion",
    "suggest.tokenRules.spend": "Soutenir le livre de quelqu'un d'autre",
    "suggest.tokenRules.earn": "+1 jeton",
    "suggest.tokenRules.cost": "−1 jeton",
    "suggest.tokenRules.limit": "Max 3 suggestions par mois · réinitialisé en début de mois",
    "suggest.form.title": "Titre",
    "suggest.form.author": "Auteur",
    "suggest.form.coverUrl": "URL de la couverture",
    "suggest.form.why": "Pourquoi ce livre ?",
    "suggest.form.titlePlaceholder": "ex. Le Grand Meaulnes",
    "suggest.form.authorPlaceholder": "ex. Alain-Fournier",
    "suggest.form.coverPlaceholder": "https://…",
    "suggest.form.whyPlaceholder": "Une courte raison pour laquelle ce livre serait un excellent choix…",
    "suggest.form.required": "Le titre et l'auteur sont obligatoires.",
    "suggest.form.submit": "Soumettre la suggestion",
    "suggest.form.update": "Mettre à jour",
    "suggest.form.saving": "Enregistrement…",
    "suggest.form.cancel": "Annuler",
    "suggest.form.edit": "Modifier votre suggestion",
    "suggest.added": "Suggestion ajoutée.",
    "suggest.updated": "Suggestion mise à jour.",
    "suggest.removed": "Suggestion supprimée.",
    "suggest.error": "Impossible d'enregistrer la suggestion. Réessayez.",
    // Past reads
    "past.title": "Lectures passées",
    "past.subtitle": "Les livres que la communauté a lus ensemble, mois après mois.",
    "past.archive": "Une archive grandissante de lectures partagées.",
    "past.back": "Retour",
    "past.viewReviews": "Voir les avis",
    "past.hideReviews": "Masquer les avis",
    "past.noReviews": "Aucun avis n'a été rédigé pour ce livre.",
    "past.empty.title": "Rien encore ici",
    "past.empty.hint": "L'archive grandira au fil des mois.",
    "past.closing": "Chaque mois ajoute un nouveau chapitre au club.",
    // Footer
    "footer.tagline": "Lire un livre ensemble chaque mois.",
    "footer.thisMonth": "Ce mois",
    "footer.howItWorks": "Comment ça marche",
    "footer.suggestions": "Suggestions",
    "footer.pastReads": "Lectures passées",
    "footer.copyright": "© 2026 The Blue Book Club — créé par Ariane S.",
    // Auth
    "auth.continue": "Continuer avec Google",
    "auth.signingIn": "Connexion…",
    "auth.signIn": "Se connecter",
    "auth.signOut.toast": "Vous êtes déconnecté.",
    "auth.signIn.error": "Échec de connexion : ",
    // Notifications
    "notifications.title": "Notifications",
    "notifications.unread": "non lus",
    "notifications.empty": "Aucune notification pour l'instant.",
    "notifications.replied": "a répondu à votre avis sur",
    // Replies
    "reply.placeholder": "Écrire une réponse…",
    "reply.post": "Répondre",
    "reply.posting": "Publication…",
    "reply.cancel": "Annuler",
    "reply.posted": "Réponse publiée.",
    "reply.error": "Impossible de publier la réponse.",
    "reply.count": "répons",
    // Discussion gate
    "past.discussionGate": "Marquez ce livre comme terminé pour rejoindre la discussion.",
  },
} as const;

type TranslationKey = keyof typeof T.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>(null!);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");
  const t = (key: TranslationKey): string => T[lang][key] ?? T.en[key] ?? key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
export type { TranslationKey };
